name: debaghy
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  badges: ^3.1.2
  cached_network_image: ^3.4.1
  carousel_slider: ^5.0.0
  change_app_package_name: ^1.3.0
  cupertino_icons: ^1.0.6
  data_connection_checker_tv: ^0.3.5-nullsafety
  dio: ^5.7.0
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_staggered_grid_view: ^0.7.0
  flutter_svg: ^2.0.10+1
  fluttertoast: ^8.2.8
  get: ^4.6.6
  get_storage: ^2.1.1
  image_picker: ^1.1.2
  intl: ^0.19.0
  pinput: ^5.0.0
  pretty_dio_logger: ^1.4.0
  shared_preferences: ^2.3.2
  url_launcher: ^6.3.0

dev_dependencies:

  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
  assets:
    - assets/images/
